name: color_app
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_color: ^2.0.0
  cupertino_icons: ^1.0.2
  flutter_styled_toast: ^2.0.0
  tinycolor2: ^2.0.0
  hex: ^0.2.0
  http: ^0.13.4
  flutter_native_splash: ^1.3.3
  url_launcher: ^6.0.17
  get: ^4.6.1
  connectivity_plus: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/Color.json
    - assets/portrait.jpg
